# Generated by Django 4.0.1 on 2022-01-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Git',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
    ]
