# Generated by Django 4.0.1 on 2022-02-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='reason',
            field=models.CharField(default='no reason', max_length=200),
            preserve_default=False,
        ),
    ]
